Repository bangkokrb/rubyconfth, pull requests merged in 2019-07, with the labels that each got.

#84 Add Gitlab as Gold sponsor
  _data/sponsors.yml
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-gitlab.jpg
Labels: priority : normal, type : feature

#85 Add Google Calendar links
  _includes/schedule.html
Labels: priority : normal, type : feature

#89 Add A-Z of practicalities guide
  _includes/map-venue.html
Labels: priority : high, type : feature

#92 List speaker sponsors
  _data/sponsors.yml
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-brightwire.jpg
  assets/images/pages/home/sponsors/logo-eventpop.jpg
  assets/images/pages/home/sponsors/logo-gitlab.jpg
  assets/images/pages/home/sponsors/logo-gojek.jpg
  assets/images/pages/home/sponsors/logo-gummy-bear.jpg
  assets/images/pages/home/sponsors/logo-josh.jpg
  assets/images/pages/home/sponsors/logo-lemi.jpg
  assets/images/pages/home/sponsors/logo-matestack.jpg
  assets/images/pages/home/sponsors/logo-nexmo.jpg
  assets/images/pages/home/sponsors/logo-nimble.jpg
  assets/images/pages/home/sponsors/logo-notion.jpg
  assets/images/pages/home/sponsors/logo-rapid-river.jpg
  assets/images/pages/home/sponsors/logo-speee.jpg
  assets/images/pages/home/sponsors/logo-wovn.jpg
  assets/images/pages/home/sponsors/logo-zero-one.jpg
Labels: priority : high, type : feature

#93 Release - 0.8.0
  _data/sponsors.yml
  _includes/map-venue.html
  _includes/schedule.html
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-brightwire.jpg
  assets/images/pages/home/sponsors/logo-eventpop.jpg
  assets/images/pages/home/sponsors/logo-gitlab.jpg
  assets/images/pages/home/sponsors/logo-gojek.jpg
  assets/images/pages/home/sponsors/logo-gummy-bear.jpg
  assets/images/pages/home/sponsors/logo-josh.jpg
  assets/images/pages/home/sponsors/logo-lemi.jpg
  assets/images/pages/home/sponsors/logo-matestack.jpg
  assets/images/pages/home/sponsors/logo-nexmo.jpg
  assets/images/pages/home/sponsors/logo-nimble.jpg
  assets/images/pages/home/sponsors/logo-notion.jpg
  assets/images/pages/home/sponsors/logo-rapid-river.jpg
  assets/images/pages/home/sponsors/logo-speee.jpg
  assets/images/pages/home/sponsors/logo-wovn.jpg
  assets/images/pages/home/sponsors/logo-zero-one.jpg
Labels: type : release

#98 Add more speakers sponsors
  _data/sponsors.yml
  assets/images/pages/home/sponsors/logo-ascenda.jpg
  assets/images/pages/home/sponsors/logo-blackmill.jpg
  assets/images/pages/home/sponsors/logo-saeloun.jpg
  lib/tasks/test.rake
Labels: priority : normal, type : feature

#97 Add the list of confirmed speakers
  _data/speakers/keynote.yml
  _data/speakers/speakers.yml
  _data/sponsors.yml
  _includes/list-keynote-speaker.html
  _includes/list-speaker.html
  _sass/components/_list-speaker.scss
  _sass/screens/_home.scss
  assets/images/pages/home/speakers/ajey-gore.jpg
  assets/images/pages/home/speakers/ajey-gore.png
  assets/images/pages/home/speakers/anton-davydov.jpg
  assets/images/pages/home/speakers/elle-meredith.jpg
  assets/images/pages/home/speakers/enrique-mogollan.jpg
  assets/images/pages/home/speakers/gabriel-fortuna.jpg
  assets/images/pages/home/speakers/giovanni-sakti.jpg
  assets/images/pages/home/speakers/harley-davidson-karel.jpg
  assets/images/pages/home/speakers/janko-marohnic.jpg
  assets/images/pages/home/speakers/jaroslava-kosanova.jpg
  assets/images/pages/home/speakers/kazuma-furuhashi.jpg
  assets/images/pages/home/speakers/leandro-ostera.jpg
  assets/images/pages/home/speakers/melvrick-chun.jpg
  assets/images/pages/home/speakers/phil-nash.jpg
  assets/images/pages/home/speakers/piotr-murach.jpg
  assets/images/pages/home/speakers/radoslav-stankov.jpg
  assets/images/pages/home/speakers/richard-schneeman.jpg
  assets/images/pages/home/speakers/richard-schneeman.png
  assets/images/pages/home/speakers/rodrigo-urubatan.jpg
  assets/images/pages/home/speakers/saron-yitbarek.jpg
  assets/images/pages/home/speakers/sergey-dolganov.jpg
  assets/images/pages/home/speakers/shweta-kale.jpg
  assets/images/pages/home/speakers/tae-wongsrinoppakun.jpg
  assets/images/pages/home/speakers/tim-riley.jpg
  assets/images/pages/home/speakers/tim-riley.png
  assets/images/pages/home/speakers/vipul-am.jpg
  assets/images/pages/home/speakers/vishal-chandnani.jpg
  assets/stylesheets/application.scss
  index.md
  lib/tasks/test.rake
Labels: priority : high, type : feature

#99 Release - 0.9.0
  _data/speakers/keynote.yml
  _data/speakers/speakers.yml
  _data/sponsors.yml
  _includes/list-keynote-speaker.html
  _includes/list-speaker.html
  _sass/components/_list-speaker.scss
  _sass/screens/_home.scss
  assets/images/pages/home/speakers/ajey-gore.jpg
  assets/images/pages/home/speakers/ajey-gore.png
  assets/images/pages/home/speakers/anton-davydov.jpg
  assets/images/pages/home/speakers/elle-meredith.jpg
  assets/images/pages/home/speakers/enrique-mogollan.jpg
  assets/images/pages/home/speakers/gabriel-fortuna.jpg
  assets/images/pages/home/speakers/giovanni-sakti.jpg
  assets/images/pages/home/speakers/harley-davidson-karel.jpg
  assets/images/pages/home/speakers/janko-marohnic.jpg
  assets/images/pages/home/speakers/jaroslava-kosanova.jpg
  assets/images/pages/home/speakers/kazuma-furuhashi.jpg
  assets/images/pages/home/speakers/leandro-ostera.jpg
  assets/images/pages/home/speakers/melvrick-chun.jpg
  assets/images/pages/home/speakers/phil-nash.jpg
  assets/images/pages/home/speakers/piotr-murach.jpg
  assets/images/pages/home/speakers/radoslav-stankov.jpg
  assets/images/pages/home/speakers/richard-schneeman.jpg
  assets/images/pages/home/speakers/richard-schneeman.png
  assets/images/pages/home/speakers/rodrigo-urubatan.jpg
  assets/images/pages/home/speakers/saron-yitbarek.jpg
  assets/images/pages/home/speakers/sergey-dolganov.jpg
  assets/images/pages/home/speakers/shweta-kale.jpg
  assets/images/pages/home/speakers/tae-wongsrinoppakun.jpg
  assets/images/pages/home/speakers/tim-riley.jpg
  assets/images/pages/home/speakers/tim-riley.png
  assets/images/pages/home/speakers/vipul-am.jpg
  assets/images/pages/home/speakers/vishal-chandnani.jpg
  assets/images/pages/home/sponsors/logo-ascenda.jpg
  assets/images/pages/home/sponsors/logo-blackmill.jpg
  assets/images/pages/home/sponsors/logo-saeloun.jpg
  assets/stylesheets/application.scss
  index.md
  lib/tasks/test.rake
Labels: type : release

#100 Fix trailing space on Melvrick
  _data/speakers/speakers.yml
Labels: type : bug

#101 Add speaker sponsor "TTY Toolkit"
  _data/sponsors.yml
  assets/images/pages/home/sponsors/logo-tty-toolkit.jpg
Labels: priority : normal, type : feature

#102 Fix: speakers list spacing
  _sass/screens/_home.scss
Labels: priority : normal, type : bug

#103 Fix CVE issue with lodash
  package-lock.json
  package.json
Labels: priority : high, type : chore

#104 Release - 0.9.1
  _data/speakers/speakers.yml
  _data/sponsors.yml
  _sass/screens/_home.scss
  assets/images/pages/home/sponsors/logo-tty-toolkit.jpg
  package-lock.json
  package.json
Labels: type : release

#107 Add Twilio as speaker sponsor
  _data/sponsors.yml
  assets/images/pages/home/sponsors/logo-twilio.jpg
Labels: priority : normal, type : feature

#105 Add tag to the keynote speaker image to different them from the general speakers
  _includes/list-keynote-speaker.html
  _sass/components/_list-speaker.scss
Labels: priority : normal, type : feature

#106 Add the complete conference schedule
  _data/schedule.yml
  _includes/header.html
  _includes/schedule.html
  _sass/components/_schedule.scss
  assets/images/pages/home/speakers/charles-nutter.jpg
  assets/images/pages/home/speakers/saron-yitbarek.png
  index.md
Labels: priority : high, type : feature

#109 Add Charles Nutter as a speaker
  _data/speakers/speakers.yml
Labels: priority : high, type : feature

#110 Release - 1.0.0
  _data/schedule.yml
  _data/speakers/speakers.yml
  _data/sponsors.yml
  _includes/header.html
  _includes/list-keynote-speaker.html
  _includes/schedule.html
  _sass/components/_list-speaker.scss
  _sass/components/_schedule.scss
  assets/images/pages/home/speakers/charles-nutter.jpg
  assets/images/pages/home/speakers/saron-yitbarek.png
  assets/images/pages/home/sponsors/logo-twilio.jpg
  index.md
Labels: type : release

#111 Add Omise as a Platinum sponsor
  _data/sponsors.yml
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-omise.jpg
Labels: priority : high, type : feature

#112 Visually differentiate sponsors who also act as partners
  _data/sponsors.yml
  _includes/list-sponsor.html
  _sass/components/_list-sponsor.scss
Labels: priority : normal, type : feature

#113 Release - 1.1.0
  _data/sponsors.yml
  _includes/list-sponsor.html
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-omise.jpg
Labels: type : release

#114 Update Gojek logo with their latest branding
  assets/images/pages/home/sponsors/logo-gojek.jpg
Labels: priority : normal, type : feature

#115 Release - 1.1.1
  assets/images/pages/home/sponsors/logo-gojek.jpg
Labels: type : release
