Repository bangkokrb/rubyconfth, pull requests merged in 2019-05, with the labels that each got.

#72 Remove S3 deployment
  .env.docker
  .env.sample
  .java-version
  Dockerfile
  Gemfile
  Gemfile.lock
  bin/deploy
  config/s3_website.yml
Labels: priority : low, type : chore

#73 Setup analytics
  _includes/analytics.html
  _layouts/default.html
  netlify.toml
Labels: priority : high, type : feature

#74 Link to the Instagram account
  _data/social_platforms.yml
  _includes/icon-sprite.svg
  assets/images/icon-sprite.svg
  assets/images/shared/icons/icon-instagram.svg
Labels: priority : normal, type : feature

#75 Add Rapid River Software as Gold sponsor
  _data/sponsors.yml
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-eventpop.jpg
  assets/images/pages/home/sponsors/logo-nimble.jpg
  assets/images/pages/home/sponsors/logo-rapid-river-software.png
Labels: priority : high, type : feature

#76 Release - 0.6.0
  .env.docker
  .env.sample
  .java-version
  Dockerfile
  Gemfile
  Gemfile.lock
  _data/social_platforms.yml
  _data/sponsors.yml
  _includes/analytics.html
  _includes/icon-sprite.svg
  _layouts/default.html
  _sass/components/_list-sponsor.scss
  assets/images/icon-sprite.svg
  assets/images/pages/home/sponsors/logo-eventpop.jpg
  assets/images/pages/home/sponsors/logo-nimble.jpg
  assets/images/pages/home/sponsors/logo-rapid-river-software.png
  assets/images/shared/icons/icon-instagram.svg
  bin/deploy
  config/s3_website.yml
  netlify.toml
Labels: type : release

#77 Fix "Richards" -> "Richard"
  _data/speakers/keynote.yml
Labels: priority : normal, type : bug

#78 Update NPM dependencies
  .babelrc
  babel.config.js
  config/webpack/shared.js
  package-lock.json
  package.json
Labels: priority : normal, type : chore
