Repository bangkokrb/rubyconfth, pull requests merged in 2019-03, with the labels that each got.

#32 As a user, I can see the application header
  _includes/footer.html
  _includes/header.html
  _layouts/default.html
  _sass/_variables.scss
  _sass/components/_app-footer.scss
  _sass/components/_app-header.scss
  _sass/components/_list-social-platform.scss
  _sass/components/_logo.scss
  _sass/layouts/default.scss
  _sass/screens/_home.scss
  assets/images/shared/2019.svg
  assets/images/shared/bangkok-strip.svg
  assets/images/shared/icons/icon-jekyll.svg
  assets/images/shared/logo/logo-text.svg
  assets/images/shared/ruby.svg
  assets/images/shared/rubyconfth.svg
  assets/stylesheets/application.scss
  index.md
Labels: priority : normal, type : feature

#33 Implement the application footer
  _includes/footer.html
  _sass/components/_app-footer.scss
  _sass/components/_logo.scss
  _sass/layouts/default.scss
  assets/images/shared/logo/logo-icon.svg
Labels: priority : normal, type : feature

#35 As a user, I can see the application navigation
  _data/social_platforms.yml
  _includes/footer.html
  _includes/header.html
  _includes/icon-sprite.svg
  _includes/list-social-platform.html
  _js/application.js
  _js/components/AppNavigation/index.js
  _js/initializers/index.js
  _js/initializers/navigation.js
  _js/polyfills/smoothscroll.js
  _layouts/default.html
  _sass/_variables.scss
  _sass/base/_typography.scss
  _sass/components/_app-footer.scss
  _sass/components/_app-navigation.scss
  _sass/components/_btn.scss
  _sass/components/_icon-hamburger.scss
  _sass/components/_logo.scss
  _sass/layouts/default.scss
  _sass/screens/_home.scss
  assets/images/icon-sprite.svg
  assets/images/shared/logo/logo-text-icon.svg
  assets/images/shared/logo/logo-text.svg
  assets/javascript/.keep
  assets/stylesheets/application.scss
  config/webpack/shared.js
  index.md
  package-lock.json
  package.json
  vendor/javascript/bootstrap/index.js
Labels: priority : high, type : feature

#36 Update all meta images with the updated logo
  _config.yml
  _includes/footer.html
  _includes/head.html
  _sass/_variables.scss
  public/images/favicon/android-icon-144x144.png
  public/images/favicon/android-icon-192x192.png
  public/images/favicon/android-icon-36x36.png
  public/images/favicon/android-icon-48x48.png
  public/images/favicon/android-icon-72x72.png
  public/images/favicon/android-icon-96x96.png
  public/images/favicon/apple-icon-144x144.png
  public/images/favicon/apple-icon-152x152.png
  public/images/favicon/favicon-16x16.png
  public/images/favicon/favicon-32x32.png
  public/images/favicon/favicon.ico
  public/images/favicon/mstile-144x144.png
  public/images/favicon/mstile-150x150.png
  public/images/favicon/mstile-310x150.png
  public/images/favicon/mstile-310x310.png
  public/images/social/og-icon.jpg
  public/images/social/opengraph.png
  public/images/social/twitter-icon.png
  public/images/social/twitter.png
  public/manifest.json
Labels: priority : normal, type : chore

#38 As a user, I can see the speakers content
  _data/speakers/keynote.yml
  _includes/footer.html
  _includes/list-keynote-speaker.html
  _sass/base/_typography.scss
  _sass/components/_app-footer.scss
  _sass/components/_link.scss
  _sass/components/_list-keynote-speaker.scss
  _sass/layouts/default.scss
  _sass/screens/_home.scss
  assets/images/pages/.keep
  assets/images/pages/home/speakers/richard-schneeman.png
  assets/images/pages/home/speakers/saron-yitbarek.png
  assets/images/pages/home/speakers/tim-riley.png
  assets/stylesheets/application.scss
  index.md
Labels: priority : normal, type : feature

#39 Feature/venue
  .env.docker
  .env.sample
  _includes/map-venue.html
  _js/components/Map/index.js
  _js/initializers/index.js
  _js/initializers/map.js
  _sass/_variables.scss
  _sass/components/_btn.scss
  _sass/components/_map-venue.scss
  _sass/components/_map.scss
  assets/stylesheets/application.scss
  config/webpack/config.dev.js
  config/webpack/config.prod.js
  index.md
Labels: priority : normal, type : feature

#40 As a user, I can see the sponsors content
  _data/sponsors.yml
  _includes/list-sponsor.html
  _sass/components/_list-keynote-speaker.scss
  _sass/components/_list-sponsor.scss
  _sass/components/_map-venue.scss
  _sass/screens/_home.scss
  assets/images/pages/home/sponsors/logo-eventpop.jpg
  assets/images/pages/home/sponsors/logo-nimble.jpg
  assets/stylesheets/application.scss
  index.md
Labels: priority : normal, type : feature

#41 As a user, I can see the sponsors content
  _sass/screens/_home.scss
  index.md
Labels: priority : high, type : feature

#42 Netlify deployment
  CNAME
  netlify.toml
Labels: priority : high, type : chore

#51 Fix: Jittery scrolling on iOS Mobile Safari
  _js/components/AppNavigation/index.js
Labels: priority : high, type : bug

#48 Replace text "Get Location" by "View Map'
  _includes/map-venue.html
Labels: priority : low, type : improvement

#46 Make the venue at the top clickable to jump to the venue section
  _includes/header.html
  _js/application.js
  _js/components/AppNavigation/index.js
  _js/screens/Home/index.js
  _js/screens/index.js
Labels: priority : normal, type : improvement

#52 Remove HTML block parsing as we don't use any Markdown syntax
  _config.yml
  _includes/list-sponsor.html
  _includes/map-venue.html
  index.md
Labels: priority : normal, type : chore

#53 Release - 0.3.1
  _config.yml
  _includes/header.html
  _includes/list-sponsor.html
  _includes/map-venue.html
  _js/application.js
  _js/components/AppNavigation/index.js
  _js/screens/Home/index.js
  _js/screens/index.js
  index.md
Labels: priority : high, type : release

#55 Update the logo for Eventpop as their branding recently changed
  assets/images/pages/home/sponsors/logo-eventpop.jpg
Labels: priority : high, type : chore

#56 Release - 0.3.2
  assets/images/pages/home/sponsors/logo-eventpop.jpg
Labels: type : release

#57 As a user, I can download the sponsorship deck #29
  _sass/screens/_home.scss
  index.md
Labels: priority : normal, type : feature

#47 There is no need for the logo at the top to link to itself
  _includes/header.html
Labels: priority : normal, type : improvement

#58 As a user I can buy tickets
  _includes/header.html
  _sass/components/_app-navigation.scss
  _sass/screens/_home.scss
  index.md
Labels: priority : high, type : feature

#59 As a user, I can join the mailing list
  _includes/footer.html
  _sass/components/_app-footer.scss
  _sass/components/_form-mailing-list.scss
  _sass/components/_form.scss
  _sass/layouts/default.scss
  _sass/mixins/_line-height.scss
  assets/stylesheets/application.scss
  vendor/stylesheets/bootstrap/bootstrap.scss
Labels: priority : high, type : feature

#60 Release - 0.4.0
  _includes/footer.html
  _includes/header.html
  _sass/components/_app-footer.scss
  _sass/components/_app-navigation.scss
  _sass/components/_form-mailing-list.scss
  _sass/components/_form.scss
  _sass/layouts/default.scss
  _sass/mixins/_line-height.scss
  _sass/screens/_home.scss
  assets/stylesheets/application.scss
  index.md
  vendor/stylesheets/bootstrap/bootstrap.scss
Labels: type : release
