Repository bangkokrb/rubyconfth, pull requests merged in 2019-08, with the labels that each got.

#116 Add separate party venue
  _data/schedule.yml
  _includes/schedule.html
  _sass/components/_schedule.scss
Labels: priority : normal, type : feature

#117 Release - 1.2.0
  _data/schedule.yml
  _includes/schedule.html
  _sass/components/_schedule.scss
Labels: type : release

#118 Add Jetbrains as Gold sponsor
  _data/schedule.yml
  _data/sponsors.yml
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-jetbrains.jpg
Labels: priority : high, type : feature

#122 Update speaker sponsor
  _data/sponsors.yml
  assets/images/pages/home/sponsors/logo-iex.jpg
  assets/images/pages/home/sponsors/logo-wovn.jpg
Labels: priority : high, type : feature

#123 Fix: Opengraph image
  _includes/head.html
Labels: priority : high, type : bug

#124 Release - 1.3.0
  _data/sponsors.yml
  _includes/head.html
  _sass/components/_list-sponsor.scss
  assets/images/pages/home/sponsors/logo-iex.jpg
  assets/images/pages/home/sponsors/logo-jetbrains.jpg
  assets/images/pages/home/sponsors/logo-wovn.jpg
Labels: type : release

#125 Fix: Invalid opengraph image path
  _includes/head.html
Labels: priority : high, type : bug

#126 Release - 1.3.1
  _includes/head.html
Labels: type : release

#127 Replace PNG logos with vector logos
  _data/schedule.yml
  _data/speakers/speakers.yml
  _data/sponsors.yml
  _includes/list-sponsor.html
  assets/images/pages/home/speakers/leandro-ostera.jpg
  assets/images/pages/home/sponsors/logo-gitlab.svg
  assets/images/pages/home/sponsors/logo-gojek.svg
  assets/images/pages/home/sponsors/logo-jetbrains.svg
  assets/images/pages/home/sponsors/logo-matestack.svg
  assets/images/pages/home/sponsors/logo-nexmo.svg
  assets/images/pages/home/sponsors/logo-nimble.svg
  assets/images/pages/home/sponsors/logo-omise.svg
  assets/images/pages/home/sponsors/logo-rapid-river.svg
Labels: priority : normal, type : feature

#128 Fix: Vishal Chandnani is too long
  _data/speakers/speakers.yml
Labels: priority : low, type : bug

#129 Fix: CVE-2019-5477
  Gemfile
  Gemfile.lock
Labels: priority : high, type : bug

#130 Release - 1.4.0
  Gemfile
  Gemfile.lock
  _data/speakers/speakers.yml
  _data/sponsors.yml
  _includes/list-sponsor.html
  assets/images/pages/home/sponsors/logo-gitlab.svg
  assets/images/pages/home/sponsors/logo-gojek.svg
  assets/images/pages/home/sponsors/logo-jetbrains.svg
  assets/images/pages/home/sponsors/logo-matestack.svg
  assets/images/pages/home/sponsors/logo-nexmo.svg
  assets/images/pages/home/sponsors/logo-nimble.svg
  assets/images/pages/home/sponsors/logo-omise.svg
  assets/images/pages/home/sponsors/logo-rapid-river.svg
Labels: type : release
