Repository bangkokrb/rubyconfth, pull requests merged in 2019-04, with the labels that each got.

#64 [#61] As a user, I can see contact email for sponshorship
  index.md
Labels: priority : normal, type : feature

#65 As a user, I can see the 4th keynote speaker
  _data/speakers/keynote.yml
  _sass/components/_list-keynote-speaker.scss
  assets/images/pages/home/speakers/ajey-gore.png
Labels: priority : high, type : feature

#66 As a user, I can see the tentative schedule content
  _includes/header.html
  _includes/schedule.html
  _sass/components/_schedule.scss
  _sass/screens/_home.scss
  assets/stylesheets/application.scss
  index.md
Labels: priority : high, type : feature

#67 Change CTA for registration to "Buy Tickets"
  _includes/header.html
  index.md
Labels: priority : normal, type : chore

#68 Replace logo image in the hero by a Bangkok-inspired illustration
  _sass/screens/_home.scss
  assets/images/pages/home/bangkok-illustration.svg
  index.md
Labels: priority : normal, type : chore

#69 Release - 0.5.0
  _data/speakers/keynote.yml
  _includes/header.html
  _includes/schedule.html
  _sass/components/_list-keynote-speaker.scss
  _sass/components/_schedule.scss
  _sass/screens/_home.scss
  assets/images/pages/home/bangkok-illustration.svg
  assets/images/pages/home/speakers/ajey-gore.png
  assets/stylesheets/application.scss
  index.md
Labels: type : release

#70 Rename Day #1 and #2 in the schedule with the actual days of the week
  _includes/schedule.html
Labels: priority : normal, type : improvement

#71 Release - 0.5.1
  _includes/schedule.html
Labels: type : release
