Repository bangkokrb/rubyconfth, pull requests merged in 2022-10, with the labels that each got.

#198 Add the venue page
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_card-venue.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_sponsor.scss
  src/images/venue/venue-day-outdoor.jpg
  src/venue.md
Labels: type : feature

#199 Add keynote speakers to the homepage
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_list-speaker.scss
  frontend/stylesheets/screens/_home.scss
  frontend/stylesheets/screens/_sponsor.scss
  src/_components/list_speaker.liquid
  src/_data/speakers.yml
  src/_data/speakers/keynote.yml
  src/_data/speakers/speakers.yml
  src/images/speakers/nate-berkopec.png
  src/images/speakers/siddarth-sharma.png
  src/index.md
  src/sponsors.md
Labels: type : feature

#201 Add the complete keynote speakers line-up
  frontend/stylesheets/screens/_home.scss
  src/_data/speakers.yml
  src/images/speakers/noah-gibbs.png
  src/images/speakers/yarden-laifenfeld.png
Labels: type : feature

#202 Add the complete keynote speakers line-up (#201)
  frontend/stylesheets/screens/_home.scss
  src/_data/speakers.yml
  src/images/speakers/noah-gibbs.png
  src/images/speakers/yarden-laifenfeld.png
Labels: type : release

#204 Minor text and grammar tweaks, fix Siddharth, improve quality of speaker images
  frontend/stylesheets/components/_list-speaker.scss
  src/_data/site_metadata.yml
  src/_data/speakers.yml
  src/images/speakers/nate-berkopec.jpg
  src/images/speakers/nate-berkopec.png
  src/images/speakers/noah-gibbs.jpg
  src/images/speakers/noah-gibbs.png
  src/images/speakers/siddarth-sharma.png
  src/images/speakers/siddharth-sharma.jpg
  src/images/speakers/yarden-laifenfeld.jpg
  src/images/speakers/yarden-laifenfeld.png
  src/index.md
  src/sponsors.md
  src/venue.md
Labels: type : chore

#205 Release - 4.2.2
  frontend/stylesheets/components/_list-speaker.scss
  src/_data/site_metadata.yml
  src/_data/speakers.yml
  src/images/speakers/nate-berkopec.jpg
  src/images/speakers/nate-berkopec.png
  src/images/speakers/noah-gibbs.jpg
  src/images/speakers/noah-gibbs.png
  src/images/speakers/siddarth-sharma.png
  src/images/speakers/siddharth-sharma.jpg
  src/images/speakers/yarden-laifenfeld.jpg
  src/images/speakers/yarden-laifenfeld.png
  src/index.md
  src/sponsors.md
  src/venue.md
Labels: type : release

#206 Add fathom analytics code
  src/_components/analytics.liquid
  src/_components/head.liquid
  src/_layouts/default.liquid
Labels: type : chore

#207 Add link to the hotel booking portal
  src/venue.md
Labels: type : feature

#208 Release - 4.2.3
  src/_components/analytics.liquid
  src/_components/head.liquid
  src/_layouts/default.liquid
  src/venue.md
Labels: type : release

#209 Add Cloud 66 sponsor
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/list_sponsor.liquid
  src/_data/sponsors.yml
  src/images/sponsors/cloud-66.svg
  src/index.md
  src/sponsors.md
Labels: type : feature

#210 Add a rough schedule
  src/_data/menu/header.yml
  src/schedule.md
Labels: type : feature

#211 Release - 4.3.0
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/list_sponsor.liquid
  src/_data/menu/header.yml
  src/_data/sponsors.yml
  src/images/sponsors/cloud-66.svg
  src/index.md
  src/schedule.md
  src/sponsors.md
Labels: type : release

#213 Fix: Fathom Analytics not working
  src/_components/head.liquid
  src/_layouts/default.liquid
  src/_layouts/home.liquid
Labels: type : bug

#214 Release - 4.3.1
  package-lock.json
  src/_components/head.liquid
  src/_layouts/default.liquid
  src/_layouts/home.liquid
  yarn.lock
Labels: type : release

#215 new logo for cloud 66
  src/images/sponsors/cloud-66.svg
Labels: type : chore

#216 Release - 4.3.2
  src/images/sponsors/cloud-66.svg
Labels: type : release

#217 add prodigy9
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/prodigy9.svg
Labels: type : chore

#218 Release - 4.3.3
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/prodigy9.svg
Labels: type : release

#219 longer prodigy sponsor desc
  src/_data/sponsors.yml
Labels: type : chore

#220 Release - 4.3.4
  src/_data/sponsors.yml
Labels: type : release

#221 Add My Cloud Fulfillment, Talented and Bee SCM sponsors
  src/_data/sponsors.yml
  src/images/sponsors/beeees.png
  src/images/sponsors/mycloudfulfillment.svg
  src/images/sponsors/talented.svg
Labels: type : feature

#222 Add practicalities page
  frontend/stylesheets/application.scss
  frontend/stylesheets/base/_typography.scss
  frontend/stylesheets/components/_section-text.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_home.scss
  frontend/stylesheets/screens/_practicalities.scss
  src/_components/section_text.liquid
  src/_data/menu/header.yml
  src/images/practicalities/hotel/direction-step-1-exit-2.jpg
  src/images/practicalities/hotel/direction-step-2-stairs.jpg
  src/images/practicalities/hotel/direction-step-3-rangnam-street..jpg
  src/images/practicalities/hotel/direction-step-4-dome.jpg
  src/images/practicalities/hotel/direction-step-5-neighbourhood.jpg
  src/images/practicalities/hotel/direction-step-6-duty-free.jpg
  src/images/practicalities/hotel/direction-step-7-hotel-signage.jpg
  src/images/practicalities/hotel/direction-step-8-hotel-lobby.jpg
  src/images/practicalities/weather.png
  src/practicalities.md
Labels: type : feature

#223 Release - 4.4.0
  frontend/stylesheets/application.scss
  frontend/stylesheets/base/_typography.scss
  frontend/stylesheets/components/_section-text.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_home.scss
  frontend/stylesheets/screens/_practicalities.scss
  src/_components/section_text.liquid
  src/_data/menu/header.yml
  src/_data/sponsors.yml
  src/images/practicalities/hotel/direction-step-1-exit-2.jpg
  src/images/practicalities/hotel/direction-step-2-stairs.jpg
  src/images/practicalities/hotel/direction-step-3-rangnam-street..jpg
  src/images/practicalities/hotel/direction-step-4-dome.jpg
  src/images/practicalities/hotel/direction-step-5-neighbourhood.jpg
  src/images/practicalities/hotel/direction-step-6-duty-free.jpg
  src/images/practicalities/hotel/direction-step-7-hotel-signage.jpg
  src/images/practicalities/hotel/direction-step-8-hotel-lobby.jpg
  src/images/practicalities/weather.png
  src/images/sponsors/beeees.png
  src/images/sponsors/mycloudfulfillment.svg
  src/images/sponsors/talented.svg
  src/practicalities.md
Labels: type : release

#225 Fix prodigy9 link
  src/_data/sponsors.yml
Labels: type : chore

#226 add sponsor proudcloud
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/proudcloud.svg
Labels: type : feature

#227 Add detailed schedule
  frontend/javascript/controllers/schedule_controller.js
  frontend/javascript/initializers/stimulus.js
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_btn.scss
  frontend/stylesheets/components/_card-talk.scss
  frontend/stylesheets/components/_form-mailing-list.scss
  frontend/stylesheets/components/_nav-tab.scss
  frontend/stylesheets/components/_table-schedule.scss
  frontend/stylesheets/screens/_home.scss
  frontend/stylesheets/screens/_schedule.scss
  frontend/stylesheets/vendor/bootstrap.scss
  src/_components/card_talk.liquid
  src/_components/table_schedule.liquid
  src/_data/schedule.yml
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
  src/_data/speakers.yml
  src/images/speakers/aaron-cruz.jpg
  src/images/speakers/anita-jaszewska.jpg
  src/images/speakers/charles-nutter.jpg
  src/images/speakers/cristian-planas.jpg
  src/images/speakers/jeremy-evans.jpg
  src/images/speakers/jonatas-davi.jpg
  src/images/speakers/michael-milewski.jpg
  src/images/speakers/paolo-perrotta.jpg
  src/images/speakers/rodrigo-urubatan.jpg
  src/images/speakers/rtdp.jpg
  src/images/speakers/selena-small.jpg
  src/images/speakers/stephan-eberle.jpg
  src/images/speakers/thatthep-vorrasing.jpg
  src/images/speakers/tim-riley.jpg
  src/images/speakers/yuji-yokoo.jpg
  src/schedule.md
Labels: type : feature

#228 Release - 4.5.0
  Gemfile.lock
  frontend/javascript/controllers/schedule_controller.js
  frontend/javascript/initializers/stimulus.js
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_btn.scss
  frontend/stylesheets/components/_card-talk.scss
  frontend/stylesheets/components/_form-mailing-list.scss
  frontend/stylesheets/components/_nav-tab.scss
  frontend/stylesheets/components/_table-schedule.scss
  frontend/stylesheets/screens/_home.scss
  frontend/stylesheets/screens/_schedule.scss
  frontend/stylesheets/vendor/bootstrap.scss
  src/_components/card_talk.liquid
  src/_components/table_schedule.liquid
  src/_data/schedule.yml
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
  src/_data/speakers.yml
  src/_data/sponsors.yml
  src/images/speakers/aaron-cruz.jpg
  src/images/speakers/anita-jaszewska.jpg
  src/images/speakers/charles-nutter.jpg
  src/images/speakers/cristian-planas.jpg
  src/images/speakers/jeremy-evans.jpg
  src/images/speakers/jonatas-davi.jpg
  src/images/speakers/michael-milewski.jpg
  src/images/speakers/paolo-perrotta.jpg
  src/images/speakers/rodrigo-urubatan.jpg
  src/images/speakers/rtdp.jpg
  src/images/speakers/selena-small.jpg
  src/images/speakers/stephan-eberle.jpg
  src/images/speakers/thatthep-vorrasing.jpg
  src/images/speakers/tim-riley.jpg
  src/images/speakers/yuji-yokoo.jpg
  src/images/sponsors/proudcloud.svg
  src/schedule.md
Labels: type : release

#229 Add schedule tweaks
  frontend/stylesheets/components/_card-talk.scss
  frontend/stylesheets/components/_table-schedule.scss
  src/_components/card_talk.liquid
  src/_components/table_schedule.liquid
  src/_data/speakers.yml
  src/images/speakers/aaron-cruz.jpg
  src/images/speakers/charles-nutter.jpg
  src/images/speakers/jonatas-davi.jpg
  src/images/speakers/noah-gibbs.jpg
Labels: type : feature

#230 Add schedule tweaks (#229)
  frontend/stylesheets/components/_card-talk.scss
  frontend/stylesheets/components/_table-schedule.scss
  src/_components/card_talk.liquid
  src/_components/table_schedule.liquid
  src/_data/speakers.yml
  src/images/speakers/aaron-cruz.jpg
  src/images/speakers/charles-nutter.jpg
  src/images/speakers/jonatas-davi.jpg
  src/images/speakers/noah-gibbs.jpg
Labels: type : release

#231 More schedule data
  src/_components/card_talk.liquid
  src/_data/speakers.yml
  src/images/speakers/anita-jaszewska.jpg
  src/images/speakers/rtdp.jpg
  src/images/speakers/selena-small.jpg
  src/index.md
Labels: type : feature

#232 Release - 4.5.2
  src/_components/card_talk.liquid
  src/_data/speakers.yml
  src/images/speakers/anita-jaszewska.jpg
  src/images/speakers/rtdp.jpg
  src/images/speakers/selena-small.jpg
  src/index.md
Labels: type : release
