Repository bangkokrb/rubyconfth, pull requests merged in 2022-11, with the labels that each got.

#233 Add Tim Riley headshot
  src/images/speakers/tim-riley.jpg
Labels: type : chore

#234 Add speaker sponsor
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/fresho.svg
  src/index.md
  src/sponsors.md
Labels: type : chore

#235 Add the speaker page
  frontend/stylesheets/application.scss
  frontend/stylesheets/base/_typography.scss
  frontend/stylesheets/components/_card-talk.scss
  frontend/stylesheets/components/_list-speaker.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_home.scss
  frontend/stylesheets/screens/_speaker.scss
  src/_components/card_talk.liquid
  src/_components/list_speaker.liquid
  src/_data/menu/header.yml
  src/_data/speakers.yml
  src/index.md
  src/speakers.md
Labels: type : feature

#236 Add community links
  frontend/stylesheets/components/_app-footer.scss
  src/_components/footer.liquid
Labels: type : feature

#237 Add Getlinks
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/getlinks.svg
Labels: type : chore

#239 Update beeees logo
  src/images/sponsors/beeees.png
Labels: type : chore

#240 Release - 4.6.1
  src/images/sponsors/beeees.png
Labels: type : release

#241 Add Facebook promo link
  netlify.toml
Labels: type : chore

#242 Release - 4.6.2
  netlify.toml
Labels: type : release

#243 Add Community Partners (styava)
  src/_data/sponsors.yml
  src/images/sponsors/styava.png
  src/index.md
  src/sponsors.md
Labels: type : chore

#244 Release - 4.6.3
  src/_data/sponsors.yml
  src/images/sponsors/styava.png
  src/index.md
  src/sponsors.md
Labels: type : release

#246 Release - 4.7.0
  frontend/stylesheets/components/_table-schedule.scss
  src/_components/table_schedule.liquid
  src/_data/schedule/day_one.yml
  src/practicalities.md
  src/venue.md
Labels: type : release
