Repository bangkokrb/rubyconfth, pull requests merged in 2022-12, with the labels that each got.

#247 speaker sponsor for jobandtalent (anita jaszewska)
  src/_data/sponsors.yml
  src/images/sponsors/jobandtalent.svg
Labels: type : chore

#248 Release - 4.7.1
  src/_data/sponsors.yml
  src/images/sponsors/jobandtalent.svg
Labels: type : release

#250 Add Anita on the spaker page
  src/_data/speakers.yml
Labels: type : chore

#249 Add Buildkite and Bluethumb as speaker sponsors
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/bluethumb.svg
  src/images/sponsors/buildkite.svg
Labels: type : feature

#251 Add the Code of Conduct page
  frontend/stylesheets/components/_app-footer.scss
  frontend/stylesheets/components/_app-header.scss
  frontend/stylesheets/components/_app-navigation.scss
  src/_components/header.liquid
  src/_data/menu/header.yml
  src/code-of-conduct.md
Labels: type : feature

#253 Add Slack redirect
  netlify.toml
Labels: type : feature

#254 Release - 4.8.1
  netlify.toml
Labels: type : release

#257 remove ticket sales
  src/_layouts/home.liquid
Labels: type : chore

#256 add slides links
  src/_components/card_talk.liquid
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
Labels: type : feature

#259 Release - 4.9.0
  Gemfile.lock
  package-lock.json
  src/_components/card_talk.liquid
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
  src/_layouts/home.liquid
  yarn.lock
Labels: type : release
