Repository bangkokrb/rubyconfth, pull requests merged in 2022-09, with the labels that each got.

#182 Update to the new conference dates
  index.md
Labels: priority : high, type : feature

#183 Release - 3.2.1
  index.md
Labels: type : release

#184 Update netlify.toml
  netlify.toml
Labels: type : feature

#186 Release - 3.2.2
  netlify.toml
Labels: type : release

#187 Add base layout for the 2022 event
  frontend/stylesheets/_variables.scss
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_app-footer.scss
  frontend/stylesheets/components/_app-header.scss
  frontend/stylesheets/components/_app-hero.scss
  frontend/stylesheets/components/_btn.scss
  frontend/stylesheets/components/_logo.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/footer.liquid
  src/_components/header.liquid
  src/_components/icon_sprite.liquid
  src/_layouts/default.liquid
  src/images/home/hero-background.png
  src/images/shared/icons/arrow-right-circle.svg
  src/index.md
Labels: type : feature

#189 Add the signed-up sponsors
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/list_sponsor.liquid
  src/_data/sponsors.yml
  src/images/sponsors/appsignal.svg
  src/images/sponsors/eventpop.png
  src/images/sponsors/honeybadger.png
  src/images/sponsors/oivan.png
  src/images/sponsors/saeloun.svg
  src/index.md
Labels: type : feature

#190 Release - 4.1.0
  frontend/stylesheets/application.scss
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/list_sponsor.liquid
  src/_data/sponsors.yml
  src/images/sponsors/appsignal.svg
  src/images/sponsors/eventpop.png
  src/images/sponsors/honeybadger.png
  src/images/sponsors/oivan.png
  src/images/sponsors/saeloun.svg
  src/index.md
Labels: type : release

#191 Fix typo in the heading for sponsors
  src/index.md
Labels: type : bug

#192 Release - 4.1.1
  src/index.md
Labels: type : release

#193 Updates sponsors
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/appsignal.svg
  src/images/sponsors/honeybadger.png
  src/images/sponsors/honeybadger.svg
  src/images/sponsors/oivan.png
  src/images/sponsors/oivan.svg
  src/images/sponsors/saeloun.svg
Labels: type : chore

#194 Update Docker setup for local development
  Dockerfile
  Gemfile.lock
  README.md
  bin/docker-start
  bin/docker-stop
  bin/start
  frontend/stylesheets/layouts/_default.scss
  package-lock.json
  package.json
  src/_components/icon_sprite.liquid
  yarn.lock
Labels: type : chore

#195 Release - 4.1.2
  Dockerfile
  Gemfile.lock
  README.md
  bin/docker-start
  bin/docker-stop
  bin/start
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_home.scss
  package-lock.json
  package.json
  src/_components/icon_sprite.liquid
  src/_data/sponsors.yml
  src/images/sponsors/appsignal.svg
  src/images/sponsors/honeybadger.png
  src/images/sponsors/honeybadger.svg
  src/images/sponsors/oivan.png
  src/images/sponsors/oivan.svg
  src/images/sponsors/saeloun.svg
  yarn.lock
Labels: type : release
