Repository bangkokrb/rubyconfth, pull requests merged in 2023-10, with the labels that each got.

#343 Rename Huy Du's talk
  src/_data/schedule/day_two.yml
Labels: type : chore

#344 Update the practicalities page
  src/practicalities.md
Labels: type : chore

#345 Release - 5.15.1
  src/_data/schedule/day_two.yml
  src/practicalities.md
Labels: type : release

#347 Add links to the speakers' slides
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
Labels: type : feature

#348 Remove the link to buy tickets
  frontend/stylesheets/components/_app-hero.scss
  src/_data/menu/header.yml
  src/_layouts/home.liquid
  yarn.lock
Labels: type : feature

#349 Release - 5.17.0
  frontend/stylesheets/components/_app-hero.scss
  package-lock.json
  package.json
  src/_data/menu/header.yml
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
  src/_layouts/home.liquid
  yarn.lock
Labels: type : release
