Repository bangkokrb/rubyconfth, pull requests merged in 2023-08, with the labels that each got.

#319 Add new JetBrains bio
  src/_data/sponsors.yml
Labels: type : chore

#320 Release - 5.11.0
  frontend/stylesheets/components/_app-navigation.scss
  frontend/stylesheets/components/_card-talk.scss
  src/_data/menu/header.yml
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
  src/_data/speakers.yml
  src/_data/sponsors.yml
  src/images/speakers/.keep
  src/schedule.md
Labels: type : release

#321 Add Steven Baker's bio and photo
  src/_data/speakers.yml
  src/images/speakers/stevenbaker.jpg
Labels: type : chore

#322 Release - 5.11.1
  src/_data/speakers.yml
  src/images/speakers/stevenbaker.jpg
Labels: type : release

#323 Add the title of Jemma's keynote talk
  src/_data/schedule/day_two.yml
Labels: type : chore

#326 Release - 5.11.2
  Gemfile.lock
  netlify.toml
  src/_data/schedule/day_two.yml
Labels: type : release

#328 Add the speaker FAQ
  frontend/stylesheets/application.scss
  frontend/stylesheets/screens/_speakerfaq.scss
  src/images/speakerfaq/5minutes.png
  src/images/speakerfaq/cruise.jpg
  src/images/speakerfaq/stage.jpg
  src/images/speakerfaq/youtube.png
  src/speaker-faq.md
Labels: type : feature

#329 Release - 5.12.0
  Gemfile.lock
  frontend/stylesheets/application.scss
  frontend/stylesheets/screens/_speakerfaq.scss
  src/images/speakerfaq/5minutes.png
  src/images/speakerfaq/cruise.jpg
  src/images/speakerfaq/stage.jpg
  src/images/speakerfaq/youtube.png
  src/speaker-faq.md
Labels: type : release
