Repository bangkokrb/rubyconfth, pull requests merged in 2023-05, with the labels that each got.

#288 Update homepage with newly confirmed keynote speaker and sponsor
  Gemfile.lock
  frontend/stylesheets/screens/_home.scss
  src/_components/list_speaker.liquid
  src/_data/speakers.yml
  src/_data/sponsors.yml
  src/_layouts/home.liquid
  src/images/speakers/banta.jpg
  src/images/speakers/matz.jpg
  src/images/sponsors/eventpop.png
  src/index.md
Labels: type : feature

#290 Update ordering of keynote speakers
  package.json
  src/_data/speakers.yml
  yarn.lock
Labels: type : chore

#291 Release - 5.4.0
  Gemfile.lock
  frontend/stylesheets/screens/_home.scss
  package-lock.json
  src/_components/list_speaker.liquid
  src/_data/speakers.yml
  src/_data/sponsors.yml
  src/_layouts/home.liquid
  src/images/speakers/banta.jpg
  src/images/speakers/matz.jpg
  src/images/sponsors/eventpop.png
  src/index.md
  yarn.lock
Labels: type : release

#293 Fix 404 speaker links
  src/_components/list_speaker.liquid
Labels: type : bug

#289 Add ticketing
  frontend/stylesheets/components/_btn.scss
  frontend/stylesheets/layouts/_default.scss
  frontend/stylesheets/screens/_home.scss
  netlify.toml
  package-lock.json
  src/_data/speakers.yml
  src/_layouts/home.liquid
  src/images/home/.keep
  src/images/home/elephant-illustration.png
  src/index.md
  yarn.lock
Labels: type : feature

#295 Fix: Center hero background on the homepage
  frontend/stylesheets/screens/_home.scss
  src/_layouts/home.liquid
Labels: type : bug

#296 Release - 5.5.1
  frontend/stylesheets/screens/_home.scss
  src/_layouts/home.liquid
Labels: type : release

#298 Release - 5.5.2
  src/_data/menu/header.yml
Labels: type : release

#299 add jemma
  frontend/stylesheets/components/_list-speaker.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/speakers.yml
  src/images/speakers/jemma.jpg
Labels: type : feature

#301 Fix name spelling issue
  src/_data/speakers.yml
Labels: type : bug

#300 Release - 5.6.0
  frontend/stylesheets/components/_list-speaker.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/speakers.yml
  src/images/speakers/jemma.jpg
Labels: type : release

#302 Add fourth keynote speaker
  frontend/stylesheets/components/_list-speaker.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/card_talk.liquid
  src/_components/list_speaker.liquid
  src/_data/speakers.yml
  src/images/speakers/ben.jpg
Labels: type : feature

#303 Add correct HTML markup
  frontend/stylesheets/components/_list-speaker.scss
  src/_components/list_speaker.liquid
Labels: type : chore

#304 Release - 6.7.0
  frontend/stylesheets/components/_list-speaker.scss
  frontend/stylesheets/screens/_home.scss
  src/_components/card_talk.liquid
  src/_components/list_speaker.liquid
  src/_data/speakers.yml
  src/images/speakers/ben.jpg
Labels: type : release
