Repository bangkokrb/rubyconfth, pull requests merged in 2023-06, with the labels that each got.

#305 Change domain for analytics
  src/_components/analytics.liquid
Labels: type : chore

#306 Remove CFP from header and button
  src/_data/menu/header.yml
  src/index.md
Labels: type : feature

#307 Release - 5.7.1
  src/_components/analytics.liquid
  src/_data/menu/header.yml
  src/index.md
Labels: type : release

#308 Add oivan as gold sponsor
  src/_data/sponsors.yml
  src/images/sponsors/oivan.svg
  src/index.md
Labels: type : feature

#309 Release - 5.8.0
  src/_data/sponsors.yml
  src/images/sponsors/oivan.svg
  src/index.md
Labels: type : release
