Repository bangkokrb/rubyconfth, pull requests merged in 2023-04, with the labels that each got.

#278 Release - 5.0.1
  Gemfile.lock
  netlify.toml
  package-lock.json
  src/practicalities.md
Labels: type : release

#279 Add a link to the CFP
  src/_data/menu/header.yml
  src/index.md
Labels: type : feature

#280 Update Gemfile.lock for ruby-lsp
  Gemfile.lock
Labels: type : chore

#281 Release - 5.1.0
  Gemfile.lock
  src/_data/menu/header.yml
  src/index.md
Labels: type : release

#283 add venue
  frontend/stylesheets/components/_app-hero.scss
  frontend/stylesheets/components/_card-venue.scss
  src/_data/menu/header.yml
  src/_layouts/home.liquid
  src/images/venue/novotel.webp
  src/venue.md
Labels: type : feature

#284 Release - 5.2.0
  Gemfile.lock
  frontend/stylesheets/components/_app-hero.scss
  frontend/stylesheets/components/_card-venue.scss
  src/_data/menu/header.yml
  src/_layouts/home.liquid
  src/images/venue/novotel.webp
  src/venue.md
Labels: type : release

#287 Release - 5.3.0
  frontend/stylesheets/screens/_home.scss
  src/_layouts/home.liquid
  src/images/speakers/opening-speaker.jpg
Labels: type : release
