Repository bangkokrb/rubyconfth, pull requests merged in 2023-07, with the labels that each got.

#310 Add new silver sponsor JetBrains
  frontend/stylesheets/components/_list-sponsor.scss
  src/_data/sponsors.yml
  src/images/sponsors/jetbrains.svg
Labels: type : feature

#313 Add Lachlan as a co-presenter
  src/_data/speakers.yml
  src/images/speakers/lachlan-hardy.jpg
Labels: type : feature

#314 Add 2023 sponsors page
  src/_data/menu/header.yml
  src/_data/sponsors.yml
  src/sponsors.md
Labels: type : feature

#315 Release - 5.10.0
  src/_data/menu/header.yml
  src/_data/speakers.yml
  src/_data/sponsors.yml
  src/images/speakers/lachlan-hardy.jpg
  src/sponsors.md
Labels: type : release

#316 Change sponsor short description
  src/_data/sponsors.yml
Labels: type : chore
