Repository bangkokrb/rubyconfth, pull requests merged in 2023-09, with the labels that each got.

#331 Add redirect to lucky draw microsite
  netlify.toml
Labels: type : feature

#330 Add two new sponsors
  Gemfile
  Gemfile.lock
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/bluethumb.svg
  src/images/sponsors/urbanoffice.svg
Labels: type : feature

#333 Fix Bluethumb sponsor information
  src/_data/sponsors.yml
Labels: type : chore

#334 Add new sponsor: Data Wow
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/datawow.svg
  src/images/sponsors/jetbrains.svg
Labels: type : feature

#335 Add new speaker: Katrina Owen
  src/_data/schedule/day_one.yml
  src/_data/speakers.yml
  src/images/speakers/faraaz-ahmad.jpg
  src/images/speakers/helio-cola.jpg
  src/images/speakers/katrina-owen.jpg
  src/images/speakers/omar.jpg
  src/images/speakers/stevenbaker.jpg
Labels: type : feature

#336 Add new speaker sponsor: WNB-RB
  src/_data/sponsors.yml
  src/images/sponsors/wnb-rb.png
  src/sponsors.md
Labels: type : feature

#337 Release - 5.14.0
  frontend/stylesheets/screens/_home.scss
  src/_data/schedule/day_one.yml
  src/_data/speakers.yml
  src/_data/sponsors.yml
  src/images/speakers/faraaz-ahmad.jpg
  src/images/speakers/helio-cola.jpg
  src/images/speakers/katrina-owen.jpg
  src/images/speakers/omar.jpg
  src/images/speakers/stevenbaker.jpg
  src/images/sponsors/datawow.svg
  src/images/sponsors/jetbrains.svg
  src/images/sponsors/wnb-rb.png
  src/sponsors.md
Labels: type : release

#338 add speaker sponsor viki for huy du
  src/_data/sponsors.yml
  src/images/sponsors/viki.png
Labels: type : feature

#340 Release - 5.14.1
  netlify.toml
  src/_data/sponsors.yml
  src/images/sponsors/viki.png
Labels: type : release

#341 Add new silver sponsor: devoteam
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/devoteam.svg
  src/images/sponsors/jetbrains.svg
Labels: type : feature

#342 Release - 5.15.0
  frontend/stylesheets/components/_list-sponsor.scss
  frontend/stylesheets/screens/_home.scss
  src/_data/sponsors.yml
  src/images/sponsors/devoteam.svg
  src/images/sponsors/jetbrains.svg
Labels: type : release
