Repository bangkokrb/rubyconfth, pull requests merged in 2023-01, with the labels that each got.

#260 Add videos and more links to the speakers' slides
  src/_components/card_talk.liquid
  src/_data/schedule/day_one.yml
  src/_data/schedule/day_two.yml
Labels: type : chore

#262 Replace link for Anita's video
  src/_data/schedule/day_two.yml
Labels: type : chore

#265 Release - 4.10.1
  src/_data/schedule/day_two.yml
Labels: type : release

#267 Release - 4.10.2
  netlify.toml
Labels: type : release

#264 Add Youtube and Mastodon to social links
  src/_components/icon_sprite.liquid
  src/_components/list_social_platform.liquid
  src/_data/social_platforms.yml
  src/images/shared/icons/mastodon.svg
  src/images/shared/icons/youtube.svg
Labels: type : feature

#269 Link past conferences on the 404 page
  frontend/stylesheets/components/_error.scss
  src/404.html
Labels: type : chore
